CREATE TABLE IF NOT EXISTS document (
    id          BIGSERIAL PRIMARY KEY,
    document_id VARCHAR(64)  NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
