package com.aicode.framework.platform.infrastructure.persistence;

import org.springframework.jdbc.core.JdbcTemplate;

import java.sql.Timestamp;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;

/**
 * 无 ORM 的 JDBC 适配器公共支撑（Week 16）。
 *
 * <p>只用 {@link JdbcTemplate} 与标准 JDBC 类型，保证同一套代码可跑在 PostgreSQL 与
 * H2（{@code MODE=PostgreSQL}）上。装配见 {@link PlatformJdbcConfiguration}。</p>
 */
public class PlatformJdbcSupport {

    private final JdbcTemplate jdbcTemplate;

    public PlatformJdbcSupport(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /** 暴露模板供同包适配器使用。 */
    public JdbcTemplate jdbc() {
        return jdbcTemplate;
    }

    /**
     * 取下一个自增主键。为兼容 PostgreSQL 与 H2，不依赖 {@code GENERATED BY DEFAULT AS IDENTITY}，
     * 统一用 {@code COALESCE(MAX(id),0)+1} 生成；写入量极小，无并发瓶颈。
     *
     * @param table    表名（仅接受本包内硬编码常量）
     * @param idColumn 主键列名
     * @return 下一个可用主键
     */
    public long nextId(String table, String idColumn) {
        Long max = jdbcTemplate.queryForObject(
                "SELECT COALESCE(MAX(" + idColumn + "), 0) FROM " + table, Long.class);
        return (max == null ? 0L : max) + 1L;
    }

    /**
     * {@link Instant} → JDBC {@link Timestamp}（UTC 语义，配合 {@code TIMESTAMP WITH TIME ZONE} 列）。
     *
     * @param instant 时间点，可为 null
     * @return JDBC 时间戳，null 原样返回
     */
    public static Timestamp toTimestamp(Instant instant) {
        return instant == null ? null : Timestamp.from(instant);
    }

    /**
     * JDBC 时间戳 → {@link Instant}，统一按 UTC 解释，避免跨时区漂移。
     *
     * @param timestamp 数据库读出的时间戳，可为 null
     * @return 时间点，null 原样返回
     */
    public static Instant toInstant(Timestamp timestamp) {
        return timestamp == null ? null : timestamp.toInstant();
    }

    /**
     * {@link OffsetDateTime} → {@link Instant}，兼容驱动直接返回带时区类型的情况。
     *
     * @param value 带时区时间，可为 null
     * @return 时间点，null 原样返回
     */
    public static Instant toInstant(OffsetDateTime value) {
        return value == null ? null : value.toInstant();
    }

    /**
     * {@link Instant} → UTC {@link OffsetDateTime}，供带时区列写入。
     *
     * @param instant 时间点，可为 null
     * @return UTC 时间，null 原样返回
     */
    public static OffsetDateTime toOffsetDateTime(Instant instant) {
        return instant == null ? null : instant.atOffset(ZoneOffset.UTC);
    }
}
